spring.application.name=car_rental
server.port=8081
spring.config.import=optional:classpath:application-local.properties

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql: true
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000
app.jwt.refresh-expiration=86400000

cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}
